### PR TITLE
Update manage.sh

### PR DESCRIPTION
**Pull request by maxpayne7978**

### CODE REVIEW

**Comment by notheotherben** [comment]
Hi @maxpayne7978, I see you've opened this and #17 to change the `tar xzf` command to `tar xfz`. Would you mind sharing the motivation behind why you've done this (ideally in the PR description)?

My understanding is that `tar`'s shortcuts are order-dependent for cases where a value is expected (such as `-f`) and that `tar xfz` would cause `tar` to attempt to read the `z` file, while `tar xzf` will instruct `tar` to:

- `x` extract a file
- `z` using gzip compression
- `f` where the file can be found at the following path...

This certainly appears to match both what we're seeing in the test suite, as well as in on the UDM that I'm personally running this on. If you're seeing anomalous behaviour elsewhere, I'd love to get that context 😄 .

**Comment by maxpayne7978** [comment]
Hi,

I ssh'd in my UDM with root privileges and use the install.sh-Script.

The Installation startet and exexute with faults:

tar invalid magic
tar short read

In my opinon, the xfz has to change in xzf. 😀

Do you had any Problems with your Installation?
Am 31. Jan. 2022, 20:23 +0100 schrieb Benjamin Pannell ***@***.***>:

**Comment by oppegard** [comment]
I ran into the same error regarding tar. The issue is that the latest tailscale release on GitHub Releases is 1.20.3, but was only released for Synology: https://github.com/tailscale/tailscale/releases

When `manage.sh` tries to download the UDM package for 1.20.3, it doesn't exist and you get a 0-byte tar file. This causes the tar error. I ran the script via `manage.sh update 1.20.2` and it worked.

**Comment by oppegard** [comment]
@notheotherben looks like you already figured out the issue in https://github.com/SierraSoftworks/tailscale-udm/tree/fix/curl-fail 🙂

**Comment by notheotherben** [comment]
Circling back here, the latest release of this package (which you should be able to install using the normal `install.sh` script, even if you've previously installed it) should no longer run into this problem.

The cause was that we were relying on GitHub Releases for a list of Tailscale versions (and to discover the latest version) and when Tailscale released v1.20.3 (for Synology devices only) we would attempt to download the corresponding package for `arm64` and fail with a 404 Not Found error.

To fix this, we've moved over to using the official Tailscale packages API to get the latest supported version, which should prevent anyone from running into this again. I appreciate your time raising this and helping us get to the bottom of it @maxpayne7978 and @oppegard.

**Pull request closed without merging**
