### PR TITLE
feat: Add initial logic for UDM-SE support

### LINKED ISSUE #31: support for UDR
hey 👋 

UDR is a little bit different than UDM, but I believe it should be pretty straightforward to support it, too

please see https://github.com/WireGuard/wireguard-vyatta-ubnt for reference, I believe the key difference is the directory tree

thank you!

### PR DESCRIPTION
**Pull request by notheotherben**
This pull request includes the first pass of adding support for the UDR/UDM-SE (and other UniFi OS 2.x devices) to this repository.

It does so by expanding the `manage.sh` script to support a plugin-style architecture which will automatically load the correct UniFi OS plugin module (1.x or 2.x) which then provides custom integration logic for each of these operating systems. UniFi OS 2.x (which is installed on the UDR and UDM-SE) is a ground-up change of how the UniFi operating system works, and removes the need for the boostchicken/on_boot script used to ensure persistence on the UDM/UDM-Pro.

Instead, we rely on the standard Tailscale `.deb` package, installing it using `dpkg -i` and then configuring `/etc/default/tailscaled` to turn on userspace networking. You'll find this implementation (and the corresponding wrappers around `systemctl start/stop/restart`) in the `package/unios_2.x.sh` file - which is the plugin module for UniFi OS 2.x.

:warning: While this PR has a test suite associated with it, it has **NOT** been tested on a live UDR/UDM-SE yet, your mileage may vary. Feedback and testing would be greatly appreciated, but please do not do so on a production device in case anything goes wrong.

## Testing Steps
To validate that this new release works correctly on your device, please follow these steps to install a prerelease version of it:

1. Download the latest release package (from the `Build / Package` pipeline) onto your device.
   ```sh
   curl -sSLq --ipv4 -o /tmp/tailscale-udm-pre.zip https://github.com/SierraSoftworks/tailscale-udm/suites/9812203326/artifacts/472244022
   ```
2. Unzip the build artifact package using `unzip -oq /tmp/tailscale-udm-pre.zip -d /tmp`
3. Un-tar the installation package into your `/data/tailscale` directory using `tar xzf /tmp/tailscale-udm.tar.gz -C /data/`
4. Run the installation command: `/data/tailscale/manage.sh install`
5. Start tailscale using `/data/tailscale/manage.sh start`

Report if you encounter any issues with the above and/or installation does not complete as expected.

### CODE REVIEW

**Comment by mfisher224** [comment]
Unable to download latest release package with that link

**Comment by notheotherben** [comment]
Thanks @DennisGaida, really appreciate the detailed information there - I've made a series of updates based on your feedback there and I'm hoping that you'll find the new installation process much more seamless.

The latest build's download link is `https://github.com/SierraSoftworks/tailscale-udm/suites/9812203326/artifacts/472244022` (and the instructions in the first post are updated to reflect this).

**Comment by epiclulz666** [comment]
i cant get the UDR to route traffic to another tailscale network with advisertised subnets. so i have a dedi linux instance on a network with 192.168.1.0/24 and i have a caravan with a UDR in it with tailscale installed and network of 192.168.12.0/24 in my tailscale console i see both online my other tailscale networks reach the  subnet 192.168.1.0/24  without issue but any device connected to the UDR in the caravan cant ping or talk to any other tailscale subnets its like its not passing traffic at all.

**Comment by notheotherben** [comment]
Hi @epiclulz666, this is expected and a limitation of us relying on userspace networking mode + the design of Tailscale's subnet routers (which are designed to expose a subnet of devices to Tailscale nodes, not the other way around).

In other words, with a subnet (192.168.1.0/24) that is exposed via a Tailscale Exit Node, it is possible to access any 192.168.1.0/24 device from a Tailscale node (ACLs permitting), however you will not be able to access any 100.0.0.0/8 devices (aka Tailscale nodes) without having Tailscale installed on the source host, nor will they be able to access any other Tailscale exposed subnets (i.e. there is no route from 192.168.1.0/24 to Tailscale).

**Pull request merged**
